services:
  mysql:
    image: mysql:8.0
    container_name: spring-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOURPASSWORD
      MYSQL_DATABASE: YOURDBNAME
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
